### PR TITLE
Add integration tests

### PR DESCRIPTION
**Pull request by gitbuda**
This is a hanging branch, the goal is to drop it or merge to master if it makes sense.

### CODE REVIEW

**Comment by gitbuda** [comment]
@antaljanosbenjamin I didn't even know that this exists, it's a nice idea, but my current thinking is we should close this because mocking Memgraph is more work, + it doesn't guarantee that everything will work with the real Memgraph instance.

What do you think?

**Comment by antaljanosbenjamin** [comment]
I think the mocks can be useful to inject errors in well specified places (e.g.: to a fetch in a fetch all or in a discard etc, just to make sure it really handles the errors well.  If I am not mistaken, then:
1. the mock will use the real instance by default
2. the extra tests are all about error handling

Therefore I think this can be useful. If you don't want to spend time on is/don't have time for this, I can take a quick look at it. If it can be done in a few hours, then merging this is a pure win in my opinion.

**Comment by gitbuda** [comment]
Yep, I was also thinking about that, mocks could be useful. Feel free to process this PR and adjust/improve :D

**Comment by gitbuda** [comment]
Closing this because it's inactive for a very long time.

**Pull request closed without merging**
